import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const sharedConfig = {
	banner: { js: banner },
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// Obsidian ships these CM6 packages at runtime.
		// We MUST externalize them to avoid version mismatches.
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
};

// Product bundle — must not contain lab machinery
const mainContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/main.ts"],
	outfile: "main.js",
});

// Telemetry/Observer bundle — FlightRecorder, DeviceWitnessTracker, DiagnosticsService
// Loaded dynamically by main.ts only when settings.debug or settings.qaDebugMode.
// Must NOT contain VFS torture, scenario steppers, unsafe CRDT/sync, network holds,
// or any mutation harness code. Mutation harness (Puppeteer) lives in qa/.
const telemetryContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/telemetry/installTelemetryRuntime.ts"],
	outfile: "telemetry.js",
});

if (prod) {
	await Promise.all([
		mainContext.rebuild(),
		telemetryContext.rebuild(),
	]);
	process.exit(0);
} else {
	await Promise.all([
		mainContext.watch(),
		telemetryContext.watch(),
	]);
}
